"""
PDF Report Generator — Application Layer

Constructs ReportLab PDF documents from data provided by ReportService.
Encapsulates all styling, tables, headers, and layouts.
"""

from io import BytesIO
from datetime import datetime, timezone
from typing import Optional, Tuple
from fastapi import HTTPException
from app.application.report_service import ReportService


def build_pdf_report(
    svc: ReportService,
    report_type: str,
    location_id: Optional[int],
    date_from: Optional[str],
    date_to: Optional[str],
    username: str,
    org_id: Optional[int],
) -> Tuple[BytesIO, str]:
    """
    Build a PDF report in memory using ReportLab.
    Returns (BytesIO buffer positioned at 0, filename).
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet
    except ImportError:
        raise HTTPException(status_code=500, detail="reportlab is not installed on the server")

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=0.75 * inch, leftMargin=0.75 * inch,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()
    elements = []

    report_titles = {
        "inventory":     "Inventory Stock Report",
        "requisitions":  "Requisitions Report",
        "low_stock":     "Low Stock Alert Report",
        "monthly_sales": "Monthly Sales & Profit Report",
    }
    title = report_titles.get(report_type, "Inventory Report")

    elements.append(Paragraph(f"InvIQ — {title}", styles["Title"]))
    elements.append(Paragraph(
        f"Generated by: {username}  |  "
        f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        styles["Normal"],
    ))
    if date_from or date_to:
        elements.append(Paragraph(
            f"Period: {date_from or 'beginning'} to {date_to or 'today'}",
            styles["Normal"],
        ))
    elements.append(Spacer(1, 0.3 * inch))

    HEADER_STYLE = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN",      (0, 0), (-1, -1), "CENTER"),
        ("GRID",       (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
    ]

    # ── INVENTORY / LOW_STOCK REPORT ──────────────────────────────────────
    if report_type in ("inventory", "low_stock"):
        rows = (
            svc.get_low_stock_rows(location_id=location_id, org_id=org_id)
            if report_type == "low_stock"
            else svc.get_stock_rows(location_id=location_id, org_id=org_id)
        )

        heading = (
            "Items Below Minimum Stock Threshold"
            if report_type == "low_stock"
            else "Current Stock Levels"
        )
        elements.append(Paragraph(heading, styles["Heading2"]))

        if not rows:
            elements.append(Paragraph("No data found for the selected criteria.", styles["Normal"]))
        else:
            def _status(r: dict) -> str:
                if r["current_stock"] <= 0:
                    return "CRITICAL"
                if r["current_stock"] <= r["min_stock"]:
                    return "WARNING"
                return "HEALTHY"

            table_data = [["Item Name", "Category", "Unit", "Current Stock", "Min Required", "Status"]]
            for r in rows:
                table_data.append([
                    r["name"][:35],
                    r["category"],
                    r["unit"],
                    str(r["current_stock"]),
                    str(r["min_stock"]),
                    _status(r),
                ])
            t = Table(table_data, colWidths=[2.2 * inch, 1 * inch, 0.6 * inch, 0.9 * inch, 0.9 * inch, 0.8 * inch])
            t.setStyle(TableStyle(HEADER_STYLE))
            elements.append(t)

    # ── REQUISITIONS REPORT ───────────────────────────────────────────────
    elif report_type == "requisitions":
        elements.append(Paragraph("Requisitions Summary", styles["Heading2"]))

        stats = svc.get_requisition_stats(date_from=date_from, date_to=date_to, org_id=org_id)
        stat_data = [
            ["Metric", "Count"],
            ["Total", str(stats["total"])],
            ["Pending", str(stats["pending"])],
            ["Approved", str(stats["approved"])],
            ["Rejected", str(stats["rejected"])],
        ]
        st = Table(stat_data, colWidths=[2.5 * inch, 1 * inch])
        st.setStyle(TableStyle(HEADER_STYLE))
        elements.append(st)
        elements.append(Spacer(1, 0.2 * inch))

        rows = svc.get_requisition_rows(date_from=date_from, date_to=date_to, org_id=org_id)
        if rows:
            elements.append(Paragraph("Requisition List", styles["Heading2"]))
            table_data = [["Req #", "Department", "Requested By", "Urgency", "Status", "Date"]]
            for r in rows:
                table_data.append([
                    r["requisition_number"],
                    r["department"],
                    r["requested_by"],
                    r["urgency"],
                    r["status"],
                    r["created_at"],
                ])
            t = Table(table_data, colWidths=[1.1 * inch, 1 * inch, 1.2 * inch, 0.8 * inch, 0.9 * inch, 0.9 * inch])
            t.setStyle(TableStyle(HEADER_STYLE))
            elements.append(t)

    # ── MONTHLY SALES REPORT ──────────────────────────────────────
    elif report_type == "monthly_sales":
        now = datetime.now(timezone.utc)
        target_year = now.year
        target_month = now.month
        if date_from:
            try:
                parts = date_from.split("-")
                target_year = int(parts[0])
                target_month = int(parts[1])
            except Exception:
                pass

        month_label = f"{target_year:04d}-{target_month:02d}"
        elements.append(Paragraph(f"Monthly Financial Performance ({month_label})", styles["Heading2"]))

        summary = svc.get_monthly_sales_summary(
            org_id=org_id or 1,
            year=target_year,
            month=target_month,
        )

        sales_data = [
            ["Financial Metric", "Value (INR)"],
            ["Total Customer Bills (Sessions)", str(summary.get("session_count", 0))],
            ["Gross Sales (MRP Total)", f"Rs. {summary.get('gross_total', 0.0):,.2f}"],
            ["Total Customer Discounts Given", f"Rs. {summary.get('discount_amount', 0.0):,.2f}"],
            ["Net Realized Revenue", f"Rs. {summary.get('net_total', 0.0):,.2f}"],
            ["Medication Purchase Cost (COGS)", f"Rs. {summary.get('purchase_cost', 0.0):,.2f}"],
            ["Gross Profit", f"Rs. {summary.get('gross_profit', 0.0):,.2f}"],
            ["Gross Profit Margin", f"{summary.get('margin_pct', 0.0):.2f}%"],
        ]
        st = Table(sales_data, colWidths=[3.2 * inch, 2.2 * inch])
        st.setStyle(TableStyle(HEADER_STYLE))
        elements.append(st)

    # Build PDF
    doc.build(elements)
    filename = f"inviq_{report_type}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M')}.pdf"
    buffer.seek(0)
    return buffer, filename
