"""initial schema from existing models

Revision ID: 2f050154dcf1
Revises: 
Create Date: 2026-07-24 17:52:28.811189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f050154dcf1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inv_tx_batch', table_name='inventory_transactions')
    op.drop_index('ix_inv_tx_expiry', table_name='inventory_transactions')
    op.create_index(op.f('ix_inventory_transactions_batch_number'), 'inventory_transactions', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_expiry_date'), 'inventory_transactions', ['expiry_date'], unique=False)
    op.alter_column('items', 'storage_temp',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'storage_temp',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'ambient'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_inventory_transactions_expiry_date'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_batch_number'), table_name='inventory_transactions')
    op.create_index('ix_inv_tx_expiry', 'inventory_transactions', ['expiry_date'], unique=False)
    op.create_index('ix_inv_tx_batch', 'inventory_transactions', ['batch_number'], unique=False)
    # ### end Alembic commands ###
